// This file was generated by the Zuplo CLI migrate-dev-portal command.
// It is used to configure the Zuplo dev portal.
// You can edit this file to customize the dev portal.
// For more information, see https://zuplo.com/docs/dev-portal/zudoku/configuration/overview
import type { ZudokuConfig } from "zudoku";

const config: ZudokuConfig = {
  site: {
    title: "Jericalla Mobile",
    logo: {
      src: {
        light: "https://cdn.zuplo.com/dev-portal/v2/made-with-zuplo.svg",
        dark: "https://cdn.zuplo.com/dev-portal/v2/made-with-zuplo.svg",
      },
      alt: "Jericalla Mobile",
      href: "/",
      width: 200,
    },
  },
  metadata: {
    title: "Jericalla Mobile",
  },
  navigation: [
    {
      type: "doc",
      file: "index",
      label: "Index",
    },
    {
      type: "doc",
      file: "accounts",
      label: "Account",
    },
    {
      type: "link",
      to: "/api",
      label: "API Reference",
    },
  ],
  apis: [
    {
      type: "file",
      input: "../config/routes-v1.oas.json",
      path: "/api/v1",
    },
    {
      type: "file",
      input: "../config/routes-v2.oas.json",
      path: "/api/v2",
    },
  ],
};
export default config;
